Repository AudiusProject/audius-mobile-client, pull requests merged in 2021-12, with the labels that each got.

#184 [AUD-1004] Trending Rewards Explainer Drawer
  package-lock.json
  package.json
  src/App.tsx
  src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  src/components/button-with-arrow/ButtonWithArrow.tsx
  src/components/button-with-arrow/index.ts
  src/components/button/Button.tsx
  src/components/button/index.ts
  src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx
  src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  src/components/drawer/Drawer.tsx
  src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  src/components/gradient-text/GradientText.tsx
  src/components/gradient-text/index.ts
  src/components/header/Header.tsx
  src/components/loading-spinner/LoadingSpinner.tsx
  src/components/loading-spinner/index.ts
  src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  src/components/notifications/List.tsx
  src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  src/components/search/Search.tsx
  src/components/search/TopBar.tsx
  src/components/signon/CreatePassword.tsx
  src/components/signon/ProfileAuto.tsx
  src/components/signon/ProfileManual.tsx
  src/components/signon/SignOn.tsx
  src/components/tab-slider/TabSlider.tsx
  src/components/tab-slider/index.ts
  src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx
  src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  src/components/trending-rewards-drawer/index.ts
  src/components/tweet-embed/TweetEmbed.tsx
  src/components/tweet-embed/index.ts
  src/hooks/useRemoteConfig.ts
  src/services/remote-config/remote-config-instance.ts
  src/store/index.ts
  src/store/sagas.ts
Labels: size/XXL

#186 Add sentry sdk
  .env.dev.tmpl
  .env.prod.tmpl
  .env.stage.tmpl
  android/app/build.gradle
  android/sentry.properties
  ios/AudiusReactNative.xcodeproj/project.pbxproj
  ios/Podfile.lock
  ios/sentry.properties
  package-lock.json
  package.json
  src/App.tsx
Labels: size/M

#188 Update client version
  package.json
Labels: size/XS

#187 Fix sentry-cli by installing in CI
  .circleci/config.yml
  ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/XS

#189 Remove unused async storage to fix android build
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/web/WebApp.tsx
  src/hooks/useRemoteConfig.ts
  src/hooks/useSessionCount.ts
  src/notifications.ts
  src/services/remote-config/remote-config-instance.ts
  src/store/search/hooks.ts
Labels: size/S

#185 [AUD-1007] Api Rewards Explainer
  package.json
  src/App.tsx
  src/assets/images/audiusAPI.png
  src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
Labels: size/L

#190 Remove console.time
  package.json
Labels: size/XS

#191 Fix type/lint issues
  src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
Labels: size/S

#192 Fix setup and CI
  .circleci/config.yml
  ios/AudiusReactNative.xcodeproj/project.pbxproj
  ios/Podfile
  ios/scripts/bundleReactNative.sh
  ios/scripts/uploadSentryDebugSymbols.sh
Labels: size/S

#196 Bump client to support hidden tracks
  package-lock.json
  package.json
Labels: size/XS

#195 Add ErrorBoundary and ToastContext to handle uncaught errors
  index.js
  src/App.tsx
  src/ErrorBoundary.tsx
  src/components/notifications/content/Cosign.tsx
  src/components/notifications/content/Favorite.tsx
  src/components/notifications/content/Follow.tsx
  src/components/notifications/content/Remix.tsx
  src/components/notifications/content/Repost.tsx
  src/components/notifications/content/Subscription.tsx
  src/components/theme/ThemeContext.tsx
  src/components/toast/ToastContext.tsx
  src/components/toast/ToastView.tsx
  src/components/web/WebApp.tsx
  src/components/web/WebRef.tsx
  src/message/handleMessage.ts
  src/message/handlers/theme.ts
  src/message/types.ts
  src/store/index.ts
  src/store/theme/actions.ts
  src/store/theme/reducer.ts
  src/store/theme/selectors.ts
  src/utils/theme.ts
Labels: size/L

#193 Get Referral From Clipboard
  README.md
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/signon/SignOn.tsx
Labels: size/M

#198 [AUD-1015] TikTok sharing
  package.json
  src/App.tsx
  src/assets/images/iconTikTok.svg
  src/assets/images/iconTikTokInverted.svg
  src/components/loading-spinner/LoadingSpinner.tsx
  src/components/oauth/OAuth.tsx
  src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  src/components/share-to-tiktok-drawer/index.ts
  src/components/signon/CreatePassword.tsx
  src/components/signon/ProfileManual.tsx
  src/components/signon/SignOn.tsx
  src/hooks/useTikTokAuth.ts
  src/store/oauth/actions.ts
  src/store/oauth/reducer.ts
  src/store/oauth/sagas.ts
  src/store/oauth/types.ts
  src/store/sagas.ts
  src/types/analytics.ts
Labels: size/L
