Repository AudiusProject/audius-mobile-client, pull requests merged in 2022-02, with the labels that each got.

#253 [AUD-1414] Forgot password helper QA Fixes
  package-lock.json
  src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
  src/components/signon/SignOn.tsx
Labels: size/S

#254 Add makeStyles pattern
  src/styles/makeStyles.ts
  src/styles/spacing.ts
  src/styles/typography.ts
Labels: size/M

#255 Add image hooks for mobile and update ExploreScreen to render featured cards
  package-lock.json
  package.json
  src/components/card/Card.tsx
  src/components/now-playing-drawer/PlayBar.tsx
  src/components/track-tile/TrackTileArt.tsx
  src/hooks/useCollectionCoverArt.ts
  src/hooks/useTrackCoverArt.ts
  src/hooks/useUserCoverPhoto.ts
  src/hooks/useUserProfilePicture.ts
  src/screens/explore-screen/components/ArtistCard.tsx
  src/screens/explore-screen/components/CollectionCard.tsx
  src/screens/explore-screen/tabs/ArtistsTab.tsx
  src/screens/explore-screen/tabs/PlaylistsTab.tsx
Labels: size/L

#258 Add Tile component, establish core components directory
  src/components/core/Tile.tsx
  src/components/core/index.ts
  src/components/track-tile/TrackTile.tsx
  src/components/track-tile/TrackTileContainer.tsx
  src/components/track-tile/TrackTileRoot.tsx
  src/components/track-tile/TrackTileSkeleton.tsx
Labels: size/L

#259 Update DynamicImage styles, rename image to source
  src/components/card/Card.tsx
  src/components/core/DynamicImage/DynamicImage.tsx
  src/components/core/DynamicImage/index.ts
  src/components/core/index.ts
  src/components/dynamic-image/index.ts
  src/components/now-playing-drawer/Artwork.tsx
  src/components/now-playing-drawer/PlayBar.tsx
  src/components/track-tile/TrackTileArt.tsx
  src/styles/index.ts
  src/styles/types.ts
Labels: size/L

#261 Improve IconButton
  package-lock.json
  src/components/core/IconButton.tsx
  src/components/core/index.ts
  src/components/icon-button/index.ts
  src/components/now-playing-drawer/ActionsBar.tsx
  src/components/now-playing-drawer/AudioControls.tsx
  src/components/track-tile/TrackTileActionButtons.tsx
  src/screens/track-screen/TrackScreenActionButtons.tsx
  src/screens/track-screen/TrackScreenHeader.tsx
  src/screens/track-screen/TrackScreenStat.tsx
Labels: size/L

#260 [AUD-1408] Add ProfilePage header
  src/assets/images/badgeArtist.svg
  src/assets/images/iconDonate.svg
  src/assets/images/iconInstagram.svg
  src/components/core/DynamicImage/DynamicImage.tsx
  src/components/core/DynamicImage/index.ts
  src/components/user-badges/UserBadges.tsx
  src/screens/profile-screen/CoverPhoto.tsx
  src/screens/profile-screen/ExpandableBio.tsx
  src/screens/profile-screen/ProfileBadge.tsx
  src/screens/profile-screen/ProfileMetrics.tsx
  src/screens/profile-screen/ProfilePhoto.tsx
  src/screens/profile-screen/ProfileScreen.tsx
  src/screens/profile-screen/ProfileSocials.tsx
  src/screens/profile-screen/ProfileTabNavigator.tsx
  src/screens/profile-screen/Sites.tsx
  src/utils/badgeTier.ts
Labels: size/XL

#263 [AUD-1439] Use common profile store
  package-lock.json
  package.json
  src/screens/profile-screen/CoverPhoto.tsx
  src/screens/profile-screen/ExpandableBio.tsx
  src/screens/profile-screen/ProfileBadge.tsx
  src/screens/profile-screen/ProfileMetrics.tsx
  src/screens/profile-screen/ProfilePhoto.tsx
  src/screens/profile-screen/ProfileScreen.tsx
  src/screens/profile-screen/ProfileSocials.tsx
  src/screens/profile-screen/Sites.tsx
Labels: size/S

#266 Update image hooks to use dispatchweb
  src/hooks/useCollectionCoverArt.ts
  src/hooks/useTrackCoverArt.ts
  src/hooks/useUserCoverPhoto.ts
  src/hooks/useUserProfilePicture.ts
Labels: size/S

#264 [AUD-1450] Add profile-page tab-navigation
  src/assets/images/iconAlbum.svg
  src/assets/images/iconCollectibles.svg
  src/assets/images/iconExploreForYou.svg
  src/assets/images/iconExploreMoods.svg
  src/assets/images/iconNote.svg
  src/assets/images/iconPlaylists.svg
  src/assets/images/iconUser.svg
  src/components/app-navigator/TopTabNavigator.tsx
  src/components/top-tab-bar/TopTabBar.tsx
  src/screens/explore-screen/ExploreScreen.tsx
  src/screens/favorites-screen/FavoritesScreen.tsx
  src/screens/profile-screen/ProfileScreen.tsx
  src/screens/profile-screen/ProfileTabNavigator.tsx
  src/screens/profile-screen/constants.ts
  src/screens/profile-screen/selectors.ts
  src/screens/profile-screen/utils.ts
  src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#265 [AUD-1409] Add profile-page tracks and reposts tabs
  src/components/lineup/Lineup.tsx
  src/components/lineup/types.ts
  src/components/now-playing-drawer/Artwork.tsx
  src/screens/profile-screen/EmptyTab.tsx
  src/screens/profile-screen/RepostsTab.tsx
  src/screens/profile-screen/TracksTab.tsx
Labels: size/L

#269 [AUD-1410] Add playlists and albums profile tab
  src/screens/profile-screen/AlbumsTab.tsx
  src/screens/profile-screen/CollectionList.tsx
  src/screens/profile-screen/PlaylistsTab.tsx
  src/screens/profile-screen/ProfileTabNavigator.tsx
Labels: size/L

#270 [AUD-1459] Refactor card lists to FlatList
  src/components/collection-list/CollectionList.tsx
  src/components/collection-list/index.ts
  src/components/core/CardList.tsx
  src/components/core/EmptyCard.tsx
  src/components/core/index.ts
  src/screens/explore-screen/tabs/ArtistsTab.tsx
  src/screens/explore-screen/tabs/PlaylistsTab.tsx
  src/screens/profile-screen/AlbumsTab.tsx
  src/screens/profile-screen/CollectionList.tsx
  src/screens/profile-screen/PlaylistsTab.tsx
  src/screens/profile-screen/ProfileScreen.tsx
  src/screens/profile-screen/RepostsTab.tsx
  src/screens/profile-screen/TracksTab.tsx
  src/styles/typography.ts
Labels: size/L

#262 Use package-lock.json as dependency cache key in CI
  .circleci/config.yml
  src/screens/track-screen/TrackScreenHeader.tsx
Labels: size/XS

#271 Refactor Card to use Tile, update Tile shadows
  src/components/card/Card.tsx
  src/components/collection-list/CollectionList.tsx
  src/components/core/CardList.tsx
  src/components/core/Tile.tsx
  src/screens/explore-screen/tabs/ArtistsTab.tsx
Labels: size/L

#268 [AUD-1383] Add support for referrals-verified challenge
  package-lock.json
  package.json
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
  src/components/challenge-rewards-drawer/ReferralRewardContents.tsx
  src/components/challenge-rewards-drawer/TwitterShareButton.tsx
Labels: size/L

#274 [AUD-1464] Merge native and mobile navigation
  src/components/track-tile/TrackTile.tsx
  src/hooks/useNavigation.ts
Labels: size/M

#275 Update upload track count
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  src/components/notifications/content/ChallengeReward.tsx
Labels: size/XS

#273 [AUD-1411] Add collectibles tab
  src/assets/images/pbIconPlay.svg
  src/components/card/Card.tsx
  src/components/gradient-text/GradientText.tsx
  src/screens/profile-screen/CollectiblesCard.tsx
  src/screens/profile-screen/CollectiblesTab.tsx
  src/screens/profile-screen/ExpandableBio.tsx
  src/screens/profile-screen/ProfileScreen.tsx
  src/screens/profile-screen/ProfileTabNavigator.tsx
  src/screens/profile-screen/utils.ts
  src/styles/makeStyles.ts
  src/styles/typography.ts
Labels: size/L

#278 [AUD-971] Add App TopBar
  src/assets/images/iconSearch.svg
  src/components/app-navigator/BottomTabNavigator.tsx
  src/components/app-navigator/TopBar.tsx
  src/components/app-navigator/TopBarArrowBack.tsx
  src/components/search/Fade.tsx
  src/hooks/useNavigation.ts
Labels: size/L

#277 [AUD-1457] Open profile page from track tile and artist card
  src/components/app-navigator/BottomTabNavigator.tsx
  src/components/app-navigator/TopBar.tsx
  src/components/search/content/SearchItem.tsx
  src/screens/explore-screen/components/ArtistCard.tsx
Labels: size/M

#279 [AUD-1479] Add support for aggregate challenges to the rewards drawer
  package-lock.json
  package.json
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
  src/components/challenge-rewards-drawer/TwitterShareButton.tsx
Labels: size/L

#281 Add notification config for referrals-verified
  src/components/notifications/content/ChallengeReward.tsx
  src/store/notifications/types.ts
Labels: size/S

#276 Add AddToPlaylistDrawer
  src/App.tsx
  src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  src/components/add-to-playlist-drawer/index.ts
  src/components/card/Card.tsx
  src/components/core/CardList.tsx
Labels: size/L

#282 Consume latest client for challenges changes
  package-lock.json
  package.json
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Labels: size/XS

#283 Add referred modal to mobile
  src/assets/images/emojis/love-letter.png
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Labels: size/S

#285 Add onLoad prop and children fix to DynamicImage
  src/components/core/DynamicImage/DynamicImage.tsx
Labels: size/S

#286 Add TextButton
  src/components/core/TextButton.tsx
  src/components/core/index.ts
  src/styles/typography.ts
Labels: size/M

#290 Bump client version
  package-lock.json
  package.json
Labels: size/XS
