Repository AudiusProject/audius-mobile-client, pull requests merged in 2022-01, with the labels that each got.

#199 [AUD-1125] Add play buttons to now playing drawer
  ios/Podfile.lock
  src/App.tsx
  src/assets/animations/iconPause.json
  src/assets/animations/iconPlay.json
  src/assets/animations/iconRepeatAllDark.json
  src/assets/animations/iconRepeatAllLight.json
  src/assets/animations/iconRepeatAllMatrix.json
  src/assets/animations/iconRepeatOffDark.json
  src/assets/animations/iconRepeatOffLight.json
  src/assets/animations/iconRepeatOffMatrix.json
  src/assets/animations/iconRepeatSingleDark.json
  src/assets/animations/iconRepeatSingleLight.json
  src/assets/animations/iconRepeatSingleMatrix.json
  src/assets/animations/iconShuffleOffDark.json
  src/assets/animations/iconShuffleOffLight.json
  src/assets/animations/iconShuffleOffMatrix.json
  src/assets/animations/iconShuffleOnDark.json
  src/assets/animations/iconShuffleOnLight.json
  src/assets/animations/iconShuffleOnMatrix.json
  src/assets/images/iconAirplay.svg
  src/assets/images/iconChromecast.svg
  src/assets/images/iconKebabHorizontal.svg
  src/assets/images/iconNext.svg
  src/assets/images/iconPrev.svg
  src/assets/images/iconVolume.svg
  src/components/animated-button/AnimatedButtonProvider.tsx
  src/components/bottom-tab-bar/BottomTabBar.tsx
  src/components/bottom-tab-bar/buttons/AnimatedBottomButton.tsx
  src/components/icon-button/IconButton.tsx
  src/components/icon-button/index.ts
  src/components/notifications/content/TwitterShare.tsx
  src/components/now-playing-drawer/ActionsBar.tsx
  src/components/now-playing-drawer/AudioControls.tsx
  src/components/now-playing-drawer/NowPlayingDrawer.tsx
  src/components/signon/SignOn.tsx
Labels: size/L

#200 [AUD-1125] Update now playing buttons
  src/assets/animations/iconFavoriteOffDark.json
  src/assets/animations/iconFavoriteOffLight.json
  src/assets/animations/iconFavoriteOffMatrix.json
  src/assets/animations/iconFavoriteOnDark.json
  src/assets/animations/iconFavoriteOnLight.json
  src/assets/animations/iconFavoriteOnMatrix.json
  src/assets/animations/iconRepostOffDark.json
  src/assets/animations/iconRepostOffLight.json
  src/assets/animations/iconRepostOffMatrix.json
  src/assets/animations/iconRepostOnDark.json
  src/assets/animations/iconRepostOnLight.json
  src/assets/animations/iconRepostOnMatrix.json
  src/assets/images/iconKebabHorizontal.svg
  src/assets/images/iconNext.svg
  src/assets/images/iconPrev.svg
  src/components/now-playing-drawer/ActionsBar.tsx
Labels: size/M

#201 Fix casing for page view event name
  src/types/analytics.ts
Labels: size/XS

#202 [AUD-1194] DynamicImage
  src/components/dynamic-image/DynamicImage.tsx
  src/components/dynamic-image/index.ts
Labels: size/L

#204 Update client to flare-51 fixes (404 safeguarding)
  package-lock.json
  package.json
Labels: size/XS

#203 Kj add env var for react native navigation
  .env.dev.tmpl
  .env.prod.tmpl
  .env.stage.tmpl
  src/components/app-navigator/AppNavigator.tsx
Labels: size/S

#205 [AUD-1212] Upgrade react-native types
  package-lock.json
  package.json
  src/components/audio/Airplay.tsx
  src/components/drawer/Drawer.tsx
  src/components/search/TopBar.tsx
  src/components/signon/CreatePassword.tsx
  src/components/signon/ProfileManual.tsx
  src/components/signon/SignOn.tsx
  src/components/toast/ToastView.tsx
Labels: size/M

#207 Disable new RN features on stage
  .env.stage.tmpl
Labels: size/XS

#209 Add ScreenHeader component and add skeleton for explore screen tab components
  src/components/top-tab-bar/TopTabBar.tsx
  src/screens/ScreenHeader.tsx
  src/screens/explore-screen/ExploreScreen.tsx
  src/screens/explore-screen/tabs/ArtistsTab.tsx
  src/screens/explore-screen/tabs/ForYouTab.tsx
  src/screens/explore-screen/tabs/MoodsTab.tsx
  src/screens/explore-screen/tabs/PlaylistsTab.tsx
  src/screens/explore-screen/tabs/TabInfo.tsx
Labels: size/L

#210 Update audius client dep hash
  package-lock.json
  package.json
Labels: size/XS

#208 [AUD-1225]: Add ShareDrawer
  src/App.tsx
  src/components/action-drawer/ActionDrawer.tsx
  src/components/notifications/content/TwitterShare.tsx
  src/components/share-drawer/ShareDrawer.tsx
  src/components/share-drawer/index.ts
  src/utils/theme.ts
  src/utils/twitter.ts
Labels: size/L

#211 Disable native nav for staging
  .env.prod.tmpl
  .env.stage.tmpl
Labels: size/XS

#214 Fix rewards amounts
  src/components/notifications/content/ChallengeReward.tsx
Labels: size/S

#212 [AUD-1161] Track Tile
  package-lock.json
  package.json
  src/assets/animations/iconFavoriteTrackTileOffDark.json
  src/assets/animations/iconFavoriteTrackTileOffLight.json
  src/assets/animations/iconFavoriteTrackTileOffMatrix.json
  src/assets/animations/iconFavoriteTrackTileOnDark.json
  src/assets/animations/iconFavoriteTrackTileOnLight.json
  src/assets/animations/iconFavoriteTrackTileOnMatrix.json
  src/assets/animations/iconRepostOffDark.json
  src/assets/animations/iconRepostOffLight.json
  src/assets/animations/iconRepostOffMatrix.json
  src/assets/animations/iconRepostOnDark.json
  src/assets/animations/iconRepostOnLight.json
  src/assets/animations/iconRepostOnMatrix.json
  src/assets/animations/iconRepostTrackTileOffDark.json
  src/assets/animations/iconRepostTrackTileOffLight.json
  src/assets/animations/iconRepostTrackTileOffMatrix.json
  src/assets/animations/iconRepostTrackTileOnDark.json
  src/assets/animations/iconRepostTrackTileOnLight.json
  src/assets/animations/iconRepostTrackTileOnMatrix.json
  src/assets/images/iconCrown.svg
  src/assets/images/iconHidden.svg
  src/assets/images/iconRepost.svg
  src/assets/images/iconStar.svg
  src/components/animated-button/AnimatedButtonProvider.tsx
  src/components/co-sign/CoSign.tsx
  src/components/co-sign/index.ts
  src/components/co-sign/types.ts
  src/components/dynamic-image/DynamicImage.tsx
  src/components/favorite-button/FavoriteButton.tsx
  src/components/favorite-button/index.ts
  src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  src/components/repost-button/RepostButton.tsx
  src/components/repost-button/index.ts
  src/components/skeleton/Skeleton.tsx
  src/components/skeleton/index.ts
  src/components/text/Text.tsx
  src/components/text/index.ts
  src/components/toast/ToastContext.tsx
  src/components/track-tile/TrackBannerIcon.tsx
  src/components/track-tile/TrackTile.tsx
  src/components/track-tile/TrackTileArt.tsx
  src/components/track-tile/TrackTileBottomButtons.tsx
  src/components/track-tile/TrackTileCoSign.tsx
  src/components/track-tile/TrackTileMetadata.tsx
  src/components/track-tile/TrackTileRankIcon.tsx
  src/components/track-tile/TrackTileStats.tsx
  src/components/track-tile/TrackTileTopRight.tsx
  src/components/track-tile/index.ts
  src/components/track-tile/styles.ts
  src/components/track-tile/types.ts
  src/components/user-badges/UserBadges.tsx
  src/models/User.ts
  src/styles/flex.ts
  src/styles/index.ts
  src/styles/typography.ts
  src/types/gesture.ts
  src/utils/badgeTier.ts
  src/utils/theme.ts
Labels: size/XXL

#217 Improve webApp render flow and missing store edge-cases
  src/App.tsx
  src/WebAppManager.tsx
  src/hooks/useSelectorWeb.ts
Labels: size/M

#216 Add optional icon to drawer title
  src/components/drawer/Drawer.tsx
Labels: size/M

#215 Add `renderIcon` prop to button, fix margins
  src/components/button/Button.tsx
Labels: size/M

#218 [AUD-1273] consume new share state, handle collections
  package-lock.json
  package.json
  src/components/share-drawer/ShareDrawer.tsx
  src/components/share-drawer/messages.ts
  src/components/share-drawer/utils.ts
Labels: size/L

#219 Upload Bounce on master
  .circleci/config.yml
Labels: size/XS

#222 [AUD-1278] Use common models
  package-lock.json
  package.json
  src/components/bottom-tab-bar/BottomTabBar.tsx
  src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
  src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  src/components/notifications/content/Cosign.tsx
  src/components/notifications/content/Remix.tsx
  src/components/notifications/content/TwitterShare.tsx
  src/components/notifications/content/UserImages.tsx
  src/components/notifications/routeUtil.ts
  src/components/share-drawer/utils.ts
  src/components/signon/SignOn.tsx
  src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  src/components/web/WebApp.tsx
  src/message/handleMessage.ts
  src/message/types.ts
  src/models/Client.ts
  src/models/Collection.ts
  src/models/Favorite.ts
  src/models/FeedFilter.ts
  src/models/OS.ts
  src/models/Playable.ts
  src/models/Repost.ts
  src/models/Stems.ts
  src/models/Theme.ts
  src/models/TimeRange.ts
  src/models/Track.ts
  src/models/User.ts
  src/models/common/Cache.ts
  src/models/common/Color.ts
  src/models/common/Identifiers.ts
  src/models/common/ImageSizes.ts
  src/models/common/Lineup.ts
  src/models/common/OnChain.ts
  src/models/common/Timestamped.ts
  src/store/lifecycle/actions.ts
  src/store/lifecycle/reducer.ts
  src/store/notifications/types.ts
  src/store/search/types.ts
  src/utils/routes.tsx
  src/utils/typeUtils.ts
Labels: size/XL

#224 Enable strict TS null checks
  src/ErrorBoundary.tsx
  src/components/app-navigator/BottomTabNavigator.tsx
  src/components/app-navigator/TopTabNavigator.tsx
  src/components/button/Button.tsx
  src/components/collectible-details-drawer/CollectibleMedia.tsx
  src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  src/components/drawer/Drawer.tsx
  src/components/dynamic-image/DynamicImage.tsx
  src/components/hcaptcha/HCaptcha.tsx
  src/components/image/AutoSizeImage.tsx
  src/components/notifications/content/Milestone.tsx
  src/components/oauth/OAuth.tsx
  src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  src/components/search/Search.tsx
  src/components/share-drawer/utils.ts
  src/components/signon/ProfileAuto.tsx
  src/components/signon/SignOn.tsx
  src/components/top-tab-bar/TopTabBar.tsx
  src/components/track-tile/TrackTileMetadata.tsx
  src/components/track-tile/TrackTileStats.tsx
  src/components/track-tile/TrackTileTopRight.tsx
  src/components/track-tile/types.ts
  src/components/user-badges/UserBadges.tsx
  src/components/web/WebApp.tsx
  src/hooks/useIsStackOpen.ts
  src/message/handlers/download.ts
  src/store/download/slice.ts
  src/utils/navigation.ts
  src/utils/routes.tsx
  tsconfig.json
Labels: size/L

#223 [AUD-1278] Use common analytics types
  src/message/index.ts
  src/types/analytics.ts
Labels: size/L

#226 [AUD-1293] Fix crash when opening link without app open
  src/hooks/useIsStackOpen.ts
Labels: size/XS

#227 Fix matrix-mode styles, toast content
  src/components/share-drawer/ShareDrawer.tsx
Labels: size/S

#229 [AUD-1303] Fix warnings & deprecations
  package-lock.json
  package.json
  src/components/theme/ThemeContext.tsx
  src/hooks/useAppState.ts
  src/store/sagas.ts
  src/utils/logging.ts
  src/utils/theme.ts
Labels: size/M

#228 [AUD-1302] Confirm that link can be opened from TweetEmbed
  src/components/tweet-embed/TweetEmbed.tsx
Labels: size/XS

#230 [AUD-1306] Add logging around null message sender
  src/utils/postMessage.ts
Labels: size/S

#233 Consume latest challenges UI
  package-lock.json
  package.json
Labels: size/XS

#232 [AUD-1276] Add shadow library, apply to NotificationBlock
  package-lock.json
  package.json
  src/components/notifications/List.tsx
  src/components/notifications/NotificationBlock.tsx
Labels: size/M

#197 [AUD-1037]Get filename from client instead of generating it
  package-lock.json
  src/message/handlers/download.ts
Labels: size/S

#213 [AUD-1223] [AUD-1005] Add ChallengeRewardsDrawer and CognitoDrawer
  src/App.tsx
  src/assets/images/iconCheck.svg
  src/assets/images/iconUpload.svg
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
  src/components/cognito-drawer/CognitoDrawer.tsx
  src/hooks/usePushRouteWeb.ts
  src/utils/theme.ts
Labels: size/XL

#234 Use hook for press scale animation on buttons
  src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  src/components/button/Button.tsx
  src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
  src/components/icon-button/IconButton.tsx
  src/components/signon/FirstFollows.tsx
  src/hooks/usePressScaleAnimation.ts
Labels: size/L

#238 [AUD-1317] Catch "Failed to delete file" error
  src/message/handlers/download.ts
Labels: size/L

#239 Npm install => npm ci
  .circleci/config.yml
Labels: size/XS

#241 [AUD-1313] Add logging around null notification entity
  src/components/notifications/NotificationBlock.tsx
Labels: size/S

#240 [AUD-1234] Add Card component
  src/components/card/Card.tsx
  src/components/card/index.ts
  src/components/dynamic-image/DynamicImage.tsx
  src/screens/explore-screen/components/ArtistCard.tsx
  src/screens/explore-screen/components/CollectionCard.tsx
  src/screens/explore-screen/tabs/ArtistsTab.tsx
  src/screens/explore-screen/tabs/PlaylistsTab.tsx
Labels: size/L

#244 Fix copy artist link
  src/components/share-drawer/utils.ts
Labels: size/XS

#242 Upgrade redux-saga from 0.16.2 to 1.1.3
  package-lock.json
  package.json
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Labels: size/XS

#243 [AUD-1283] Create forgot password drawer
  src/App.tsx
  src/assets/images/iconQuestionMark.svg
  src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
  src/components/forgot-password-drawer/index.ts
  src/components/signon/SignOn.tsx
  src/store/drawers/slice.ts
Labels: size/L

#237 [AUD-1329]Add fastlane device refresh script to run when updating the list of devices
  package-lock.json
  package.json
Labels: size/XS

#246 Update AnimatedButton to be controlled
  src/components/animated-button/AnimatedButtonProvider.tsx
  src/components/favorite-button/FavoriteButton.tsx
  src/components/repost-button/RepostButton.tsx
Labels: size/S

#245 [AUD-1122] Add play bar to now playing drawer
  src/components/drawer/Drawer.tsx
  src/components/now-playing-drawer/ActionsBar.tsx
  src/components/now-playing-drawer/AudioControls.tsx
  src/components/now-playing-drawer/Logo.tsx
  src/components/now-playing-drawer/NowPlayingDrawer.tsx
  src/components/now-playing-drawer/PlayBar.tsx
  src/components/now-playing-drawer/TrackingBar.tsx
Labels: size/L

#248 [AUD-1381] Fix drawer border 0 bug
  src/components/drawer/Drawer.tsx
Labels: size/XS

#247 [AUD-1122] Connect play bar
  src/components/now-playing-drawer/NowPlayingDrawer.tsx
  src/components/now-playing-drawer/PlayBar.tsx
  src/components/now-playing-drawer/TrackingBar.tsx
Labels: size/L

#250 Fix Btn underlay color
  src/components/button/Button.tsx
Labels: bug, size/XS

#249 [AUD-1162] Lineup
  metro.config.js
  package-lock.json
  package.json
  src/assets/animations/iconFavoriteTrackTileOffLight.json
  src/components/animated-button/AnimatedButtonProvider.tsx
  src/components/bottom-tab-bar/BottomTabBar.tsx
  src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  src/components/dynamic-image/DynamicImage.tsx
  src/components/favorite-button/FavoriteButton.tsx
  src/components/image-skeleton/ImageSkeleton.tsx
  src/components/image-skeleton/index.ts
  src/components/lineup/Delineator.tsx
  src/components/lineup/Lineup.tsx
  src/components/lineup/delineate.ts
  src/components/lineup/index.ts
  src/components/lineup/types.ts
  src/components/repost-button/RepostButton.tsx
  src/components/track-tile/TrackTile.tsx
  src/components/track-tile/TrackTileArt.tsx
  src/components/track-tile/TrackTileBottomButtons.tsx
  src/components/track-tile/TrackTileContainer.tsx
  src/components/track-tile/TrackTileMetadata.tsx
  src/components/track-tile/TrackTileRankIcon.tsx
  src/components/track-tile/TrackTileSkeleton.tsx
  src/components/track-tile/TrackTileStats.tsx
  src/components/track-tile/TrackTileTopRight.tsx
  src/components/track-tile/index.ts
  src/components/track-tile/styles.ts
  src/components/track-tile/types.ts
  src/hooks/useRemoteConfig.ts
  src/hooks/useSelectorWeb.ts
  src/screens/feed-screen/FeedScreen.tsx
  src/screens/track-screen/TrackScreen.tsx
  src/store/audio/selectors.ts
  src/styles/flex.ts
  tsconfig.json
Labels: size/XXL

#252 Prevent render of disabled native screens
  src/components/app-navigator/AppNavigator.tsx
  src/components/app-navigator/BottomTabNavigator.tsx
Labels: size/S
